### ISSUE TITLE
migrate from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by RonanHiggins** [ccatobs/MODBUS#11]
This will allow for easier integration into docker containers.
also cuts down in number of file, just a single file instead of a setup.py and requirements.txt

**Comment by Tamburasca** [comment]
updated, branch dev is up to date with master. what about the other branches. can they be deleted?

**Comment by RonanHiggins** [comment]
Thanks Ralf, leave that 7 branch, I still have dreams of a bulk_read function but agree with your original thought that for some modbus registers (those spread of 1000s of addresses ) it will be difficult to find a generic solution.. The other branches you can drop..

**Comment by Tamburasca** [comment]
Yes Sir, we'll reactivate the bulk stuff, in case we find ourselves in a dead end. Pls keep in mind that pymodbus is 2 minor release ahead of us.

**Comment by Tamburasca** [comment]
Regarding bulk, I found the following comment in the most recent docs:

The quantity of registers to be read, combined with all other fields in the expected response, must not exceed the allowable length of the MODBUS PDU: 235 bytes.
